// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOExnzl-KqosoSeTCE8HxLJj8DaF7gKs',
    appId: '1:767960927938:web:e08cef438ef74a0844b55b',
    messagingSenderId: '767960927938',
    projectId: 'untitled1-28309',
    authDomain: 'untitled1-28309.firebaseapp.com',
    storageBucket: 'untitled1-28309.appspot.com',
    measurementId: 'G-LTV3T29CSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbXlzblVDuxbho6wKDzYkEPERKGZHQLs',
    appId: '1:767960927938:android:1f24767e57e2f1fc44b55b',
    messagingSenderId: '767960927938',
    projectId: 'untitled1-28309',
    storageBucket: 'untitled1-28309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3t1A2CMa3DyxVSL4DsWIxGWZIDJ8sg0s',
    appId: '1:767960927938:ios:5aafecc3c0cc624844b55b',
    messagingSenderId: '767960927938',
    projectId: 'untitled1-28309',
    storageBucket: 'untitled1-28309.appspot.com',
    iosClientId: '767960927938-70ll0sliamrrv1fm2at83avscfjthj0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3t1A2CMa3DyxVSL4DsWIxGWZIDJ8sg0s',
    appId: '1:767960927938:ios:1adbf8d3c0c92c7244b55b',
    messagingSenderId: '767960927938',
    projectId: 'untitled1-28309',
    storageBucket: 'untitled1-28309.appspot.com',
    iosClientId: '767960927938-caa80v4doast7h0j5o9bllqgo73aoi3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
